//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marker()
        {
            this.Register = new HashSet<Register>();
        }
    
        public int MarkerID { get; set; }
        public string Marker1 { get; set; }
        public string Url { get; set; }
        public string English { get; set; }
        public string Spanish { get; set; }
        public string Italian { get; set; }
        public string French { get; set; }
        public string German { get; set; }
        public string Portuguese { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Register { get; set; }
    }
}
