//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoronaV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RegByCity
    {
        public int RegisterID { get; set; }
        public string Latlng { get; set; }
        public string Message { get; set; }
        public int MarkerID { get; set; }
        public string Url { get; set; }
        public int CityID { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string ImageHtml { get; set; }
        public string Contact { get; set; }
    }
}
